name: Playwright Tests
on:
  push:
    branches: [master]

env:
  user_password: ${{ secrets.user_password}}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run API Test
      run: npx playwright test tests/api
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-api
        path: playwright-report/
        retention-days: 30

    - name: Run E2E Test
      run: npx playwright test tests/e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-e2e
        path: playwright-report/
        retention-days: 30
